name: Ubuntu
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
          linux-local-args: '["--toolkit"]'      
 
      - name: Checkout
        uses: actions/checkout@v2      

      - name: Install dependencies
        run: sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev libmicrohttpd-dev

      - name: Create build directory
        run: mkdir ${{github.workspace}}/build      

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -DWITH_HTTPD=OFF -DCUDA_LIB=/usr/local/cuda-11.5/lib64/stubs/libcuda.so -DCUDA_ARCH=50

      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j      

      - run: echo "This job's status is ${{ job.status }}."

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-ubuntu-latest
          path: |
            ./build/xmrig-nvidia