name: Windows
on: push
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download XMRig Dependencies
        uses: actions/checkout@v2 
        with:
          repository: 'xmrig/xmrig-deps'
          path: 'xmrig-deps'

      - name: Install dependencies
        run: |
          choco install ninja

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
          linux-local-args: '["--toolkit"]'     

      - run: nvcc -V

      - name: Create build directory
        run: |
          mkdir ./build   

      - name: Configure CMake
        run: |
          $XmRigDeps = Join-Path "${{ github.workspace }}" "xmrig-deps\msvc2019\x64"
          cd ./build  
          cmake ../ -G "Visual Studio 16 2019" -A x64 -DWITH_HTTPD=OFF -DCUDA_ARCH="50" -DXMRIG_DEPS="$XmRigDeps"

      - name: Compile
        run: |
          rm ../CMakeCache.txt
          cmake --build . --config Release    

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-windows-latest
          path: |
            ./xmrig-nvidia.exe