name: Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: true
          install: >-
            mingw-w64-x86_64-libuv
            mingw-w64-x86_64-hwloc
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-libmicrohttpd
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-gcc
            base-devel
            git

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
          linux-local-args: '["--toolkit"]'     

      - name: Create build directory
        run: mkdir ./build      

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cd ./build
          cmake ../ -DWITH_HTTPD=OFF -DCUDA_ARCH=50

      - name: Run make
        shell: msys2 {0}
        run: |
          cd ./build
          make -j      

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-windows-latest
          path: |
            ./build/xmrig-nvidia.exe